### ISSUE TITLE
Installation on Mac?

### ISSUE THREAD

**Issue by DeFilippis** [QueensGambit/CrazyAra#23]
Is there any way you can provide an installation guide for the latest version of CrazyAra on a Mac?  I can't seem to compile cutechess for use on a Mac. 

Thanks

**Comment by QueensGambit** [comment]
Hi @DeFilippis,
installing cutechess on Mac is a bit tricky and because I don't have a Mac I can't test it myself.
I created a pull-request on cutechess some while ago with more detailed instructions for Mac:
* https://github.com/cutechess/cutechess/pull/475

Here's also a post if you also want to make Stockfish run on your mac, too:
* https://lichess.org/forum/team-crazyhouse-engine-development-and-game-analyses/re-how-to-run-crazyhouse-stockfish-on-a-mac

**Comment by DeFilippis** [comment]
Has there been any progress made on getting a version of CrazyAra to work for Mac?  I tried cutechess back in April and couldn't get it to work.

**Comment by QueensGambit** [comment]
Thanks for your recurring interest @DeFilippis.

Yes, there are alternative graphical user interfaces which support chess variants, including crazyhouse:

[XBoard](https://www.gnu.org/software/xboard/) is available for Linux and Mac:

* https://www.macupdate.com/app/mac/54918/xboard
* https://mac.softpedia.com/get/Games/XBoard.shtml#download

In the case of Windows the corresponding software is called Winboard.

Norbert Raimund Leisner appears to have successfully imported the python version of CrazyAra into WinBoard:
* http://talkchess.com/forum3/viewtopic.php?t=70920

The newest _CrazyAra_ release 0.6.0 is written in C++, but I was unable to provide an OSX-binary for it.
Therfore, I can give you instructions on how to setup the latest python **version 0.5.1** in XBoard:

After installing Python on OSX [directly](https://www.python.org/downloads/mac-osx/) or via [anaconda](https://docs.anaconda.com/anaconda/install/mac-os/), you need the python-packages MXNet and python-chess as well:

```
pip install mxnet
pip install python-chess
```

More detailed information on this can be found in the first part of the installation guide:
* https://github.com/QueensGambit/CrazyAra/wiki/Installation-Guide

---

Next you download and extract release [CrazyAra_0.5.1_RiseV2_mobile](https://github.com/QueensGambit/CrazyAra/releases/download/0.5.1/CrazyAra_0.5.1_RiseV2_mobile.zip).

After launching XBoard, navigate to the menu:
```
Engine-> Load New 1st engine
```

Here you set the fields **"Engine Directory"** and **"Engine Command"** and set the checkbox **"UCI"**.

![load_crazyara](https://raw.githubusercontent.com/QueensGambit/CrazyAra/master/etc/media/wiki/Install_Guide/xboard/load_crazyara.png)

**Engine Directory** `/home/<username>/Desktop/CrazyAra_0.5.1_RiseV2_mobile`

**Engine Command** `/home/<username>/anaconda3/bin/python crazyara.py`

You need to change `/home/<username>/anaconda3/bin/python` into `/usr/bin/python` if you installed python without using anaconda.


The settings of the registered engines can still later be modified using
```
Engine->Edit Engine List...
```

![registered_engines](https://raw.githubusercontent.com/QueensGambit/CrazyAra/master/etc/media/wiki/Install_Guide/xboard/registered_engines.png)


Afterwards you can inspect the engine settings using:
```
Engine-> Engine #1 Settings...
```

![crazyara_settings](https://raw.githubusercontent.com/QueensGambit/CrazyAra/master/etc/media/wiki/Install_Guide/xboard/crazyara_settings.png)

The most important setting to change is
`context cpu` into `context gpu`
if you have a Nvidia CUDA compatible GPU, CUDA and mxnet-cuXX installed.


Using the ```Mode``` menu, you can either play as white, black or create an engine vs engine match.

I was able to start a classical chess match, but unfortunately it seems that XBoard was unable to properly detect that CrazyAra supports the crazyhouse variant.
![unsupported_variant](https://raw.githubusercontent.com/QueensGambit/CrazyAra/master/etc/media/wiki/Install_Guide/xboard/unsupported_variant.png)
The match concluded normally until CrazyAra attempted a dropping move which was marked illegal by XBoard.
I encountered the same problem when trying to integrate [Multi-Variant-Stockfish](https://github.com/ddugovic/Stockfish) into XBoard.
Thus, I either missed a specific setting or it could be a bug in XBoard.

If you face the same problem on Mac, then I can try to contact the developer team about it.

There is also the  [PyChess](http://pychess.org/) GUI which should in principle also run on OSX.
However, the GUI appears not be available for OSX, yet.
* https://github.com/pychess/pychess/issues/1757

**Comment by DeFilippis** [comment]
Hey Johannes, 

Thanks so much for the detailed tutorial.  Unfortunately, I experienced the same issue as you (XBoard was unable to recognize CrazyAra as a Crazyhouse variant, and automatically crashed after an illegal move).  I suggest contacting the developer team if you have any free time!  I'd love to be able to analyze openings with CrazyAra, but there seems to be no easy way to do so on a Mac

Thanks again!

**Comment by QueensGambit** [comment]
Nice to hear that you managed to get it work to the same point as me.
I just wrote an email to the XBoard developers which describes our problem.

In the meantime you can also run _CrazyAra_ from the command-line to analyse a position.

After starting using
```
python crazyara.py
```
you can specify engine options like this:

```
setoption name context value gpu
```

The default settings can alternatively be set in the file `crazyara.py` under `self.settings` directly.
Next, you use:
```
isready
```
to load the neural network.

In order to setup a specific game position use:
```
position fen rnbqkb1r/pppp1ppp/5n2/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R/ w KQkq - 4 3
```
or 
```
position startpos moves e2e4 e7e5
```
if you want to input a sequence of moves. This is for example needed to detect a 3-fold-repetition.

---

To start a search for X amount of mill-seconds use:
```
go movetime 5000
```
or for a specific depth:
```
go depth 20
```

More information about the UCI protocoll can be found [here](http://wbec-ridderkerk.nl/html/UCIProtocol.html).


The [lichess.org opening explorer](https://lichess.org/analysis/crazyhouse#0) can be used for selecting a specific board and copy over the FEN.

---

If you are bit used to python and jupyter notebooks, then you can also try out the notebook [MCTS_eval_demo.ipynb](https://github.com/QueensGambit/CrazyAra/blob/master/DeepCrazyhouse/src/samples/MCTS_eval_demo.ipynb).
Here you can inspect the raw-network policy and plots of the node statistics after the MCTS search.

The raw network policy should closely relate to the move preferences of the human player base with an Elo rating > 2000.

For getting the notebook to run, you need to specify the paths for the neural network as described in the corresponding [README](https://github.com/QueensGambit/CrazyAra/blob/master/DeepCrazyhouse/src/samples/README.md).

**Comment by QueensGambit** [comment]
Hello  @DeFilippis,

I received an answer from H.G. Muller and was able to import _Multi-Variant-Stockfish_, _CrazyAra_ (Python-Version) and _CrazyAra_ (C++ version) into XBoard to play the crazyhouse variant.

The reason why, it didn't recognize the crazyhouse variant for both UCI engines was because by default it uses the **Polyglot** adapter to translate UCI into the XBoard communication protocol.
**Polyglot** only supports classical Chess, Chess960 and is unaware that UCI engines might play other variants as well.

As a solution you can use the more modern **uci2wb** adapter instead.
On Debian systems this fairly easy to install:

`sudo apt-get install uci2wb`

but it seems that this adapter is also available for OSX:

* http://www.open-aurec.com/wbforum/viewtopic.php?t=53274
* http://www.talkchess.com/forum3/viewtopic.php?t=54162

Afterwards you can launch XBoard like this to use **uci2wb** by default:
```
xboard -adapterCommand {uci2wb debug "%fcp" "%fd"}
```

_Multi-Variant-Stockfish_ and the _CrazyAra_ (C++ Version) was working out of the box.
For the _CrazyAra_ (Python-Version), I needed to create a small shell script `crazyara.sh`:
 
```bash
#!/bin/sh
python crazyara.py
```

I added the file into the release [CrazyAra 0.5.1](https://github.com/QueensGambit/CrazyAra/releases).

Now, you should be able to integrate _CrazyAra_ in a similar way as previously mentioned into XBoard.

`Engine->Edit Engine List...`
```
"CrazyAra-0.5.1"
-fcp "/home/<username>/Desktop/CrazyAra_0.5.1_RiseV2_mobile/crazyara.sh"
-fd "/home/<username>/Desktop/CrazyAra_0.5.1_RiseV2_mobile" -fUCI
```

**Comment by DeFilippis** [comment]
Thanks a lot for all your help on this. Unfortunately, I couldn't get the latest Mac versions of CrazyAra to work with XBoard. Has there been any updates on this front on easier ways to make CrazyAra work on Mac? Does CuteChess work with CrazyAra yet?

**Comment by QueensGambit** [comment]
Hi, I just build the [**CuteChess 1.2.0** release](https://github.com/cutechess/cutechess/releases/tag/1.2.0) by [statically linking](https://retifrav.github.io/blog/2018/02/17/build-qt-statically/) to the Qt 5.12 library (open-source).
You can find the release files here:
* https://github.com/QueensGambit/cutechess/releases/tag/1.2.0

By using static instead of dynamic linking it should work out of the box on your system because the executable has only system library dependencies.
```
otool -L Cute\ Chess 
Cute Chess:
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 162.0.0)
	/System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore (compatibility version 1.2.0, current version 1.11.0)
	/System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (compatibility version 1.2.0, current version 1.5.0)
	/System/Library/Frameworks/Metal.framework/Versions/A/Metal (compatibility version 1.0.0, current version 212.5.15)
	/System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libcups.2.dylib (compatibility version 2.0.0, current version 2.14.0)
	/System/Library/Frameworks/CoreText.framework/Versions/A/CoreText (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1355.13.0)
	/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1894.40.150)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 59306.101.1)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 52.0.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1069.22.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1675.129.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1675.129.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

Please let me know if it works.
Note, however, that CuteChess is primarily used for conducting engine tournaments and not for doing opening analysis.

In 2020, I started a cross-plattform project called [**LiGround**](https://github.com/ml-research/liground) which has the goal to make chess variant analysis more convinient. The project is currently being continued by a group of students and the first version with binaries is expected to be released in the next few weeks.

**Comment by DeFilippis** [comment]
Thanks so much for your endless patience. I finally got it to work! I see now what you're saying about CuteChess and opening analysis. Is there any way to trick CuteChess into analyzing a position rather than playing a game??

**Comment by QueensGambit** [comment]
Great, to hear that the release is working on Mac.
Some features for opening analysis are still missing in CutChess:
* https://github.com/cutechess/cutechess/issues/463
* https://github.com/cutechess/cutechess/issues/284

There are few tricks to use CuteChess for analysis.
For instance, you can define a epd file with a given [list of FEN positions](https://github.com/ianfab/books/blob/master/crazyhouse_mix_cp_130.epd) that you are interested in.
Next, you can set a tournament where you set this epd file as your opening suite.
In _CrazyAra_ you can set a fixed number of nodes per move using the UCI-options (`Nodes`, `Simulations` or `playouts_empty_pockets`, `playouts_filled_pockets`) depending on the used version.
 This way it will ignore the given time control and you can use the time control to adjudicate the game after a few moves.
In the tournament creator you can set a PGN output to save all resulting games in a PGN file annotated with _CrazyAra's_ search evaluation.

**Comment by QueensGambit** [comment]
> Hello @DeFilippis,
> 
> I received an answer from H.G. Muller and was able to successfully import _Multi-Variant-Stockfish_, _CrazyAra_ (Python-Version) and _CrazyAra_ (C++ version) into XBoard to play the crazyhouse variant.
> 
> The reason why, it didn't recognize the crazyhouse variant for both UCI engines was because by default it uses the **Polyglot** adapter to translate UCI into the XBoard communication protocol.
> **Polyglot** only supports classical Chess, Chess960, and is unaware that UCI engines might play other variants as well.
> 
> As a solution you can use the more modern **uci2wb** adapter instead. [...]

I was informed, that the **uci2wb** adapter has been integrated into **Winboard 4.9**, which is based on  **XBoard 4.9** and is now available as an alpha version:
* http://hgm.nubati.net/WinBoard-AA.zip

**Comment by DeFilippis** [comment]
Thanks so much, but I'm confused as to how I'm supposed to use this. The **uci2wb** adapter included in that zip file is Windows executable, so I'm not sure how to use it.

**Comment by QueensGambit** [comment]
Yes, **Winboard 4.9.1a** is related to Windows, but there is also an also an **XBoard 4.9.1a** release for OSX with **UCI2WB** included.
* http://www.open-aurec.com/wbforum/viewtopic.php?t=53680
* https://mac.softpedia.com/get/Games/XBoard.shtml#download

_Mutli-Variant-Stockfish_ was working for crazyhouse then.
* https://github.com/ddugovic/Stockfish/releases

When trying _CrazyAra-0.8.0_, however I received the error:

> "Variant crazyhouse is not available for CrazyAra 0.8.0 (UCI2WB), but crazyhouseouse is."

This seems to be a parsing bug of XBoard/Winboard to me when it tries to read a combo box in the UCI options with only a single available entry:
`option name UCI_Variant type combo default crazyhouse var crazyhouse`
After I changed this line into:
`option name UCI_Variant type combo default crazyhouse var crazyhouse var crazyhouse`
_CrazyAra_ was working in XBoard on Mac as well.

I'll keep this limitation in mind for the next release, and will add a duplicate entry if a binary has only a single UCI_Variant available.

**Comment by DeFilippis** [comment]
Hello again, and thanks for your patience. I'm still not able to get a working version of XBoard to run CrazyAra. I think I may be missing a few key steps in your instructions. Let me explain the steps that I followed:

1. I downloaded XBoard from here: https://mac.softpedia.com/get/Games/XBoard.shtml#download (which presumably contains the UCI2WB adapter).

2. I run the `XBoard_4.9.1a_OSX_Intel.dmg` file. It doesn't install like a traditional app, it instead opens up in the Mac sidebar under locations. I double click on the XBoard icon and it boots up a functioning copy of XBoard.

3. I download the latest version of CrazyAra available for Mac OS here: https://github.com/QueensGambit/CrazyAra/releases/download/0.8.0/CrazyAra_0.8.0_Mac_CPU.zip

4. I select "Edit Engine List" and navigate to the recently unzipped CrazyAra directory for the "Directory" field. For the "Engine" field, I simply select the CrazyAra executable. 

<img width="601" alt="Screen Shot 2021-02-01 at 11 25 29 AM" src="https://user-images.githubusercontent.com/308931/106486957-330ccb00-6480-11eb-8871-f567525e512d.png">

5. I immediately get the error: `POLYGLOT: pipex_open() execvp(): [My directory] No such file or directory`

I cannot find where I'm supposed to be modifying the following line: 

`option name UCI_Variant type combo default crazyhouse var crazyhouse

Since this doesn't appear in the "Edit Engine List" txt file.

Would really appreciate any way you can advise.

Thanks!

**Comment by DeFilippis** [comment]
Edit: I just discovered the source of the error. You cannot put CrazyAra inside any directory containing periods or spaces, otherwise it won't be parsed by XBoard. 

However, I still can't find where to modify the following line: `option name UCI_Variant type combo default crazyhouse var crazyhouse`

**Comment by QueensGambit** [comment]
Hi @DeFilippis , I am sorry for the confusion.
The line `option name UCI_Variant type combo default crazyhouse var crazyhouse` is something, the engine returns after GUI sends the `uci` command.
The comand `uci` is part of the [**UCI-protocol**](http://wbec-ridderkerk.nl/html/UCIProtocol.html).
I had to modify and recompile the _CrazyAra_ binary to make it work.

Besides that, I just compiled _CrazyAra 0.8.4_ from current master (commit: bb17e4d2e55b676ed16a60bf7c6b42d694b6de8a) to [Google-Drive](https://drive.google.com/drive/folders/1HaqVOfJJxr_Szqtqcl915Uh78EHj92z3?usp=sharing) for Mac.
You should be able to directly replace the old _CrazyAra_ binary with this version and use it in XBoard on Mac.

If you run into an error, let me know.

**Comment by DeFilippis** [comment]
Thanks for your prompt reply! You were right you have to do `chmod +x ./CrazyAra`. It's also necessary to first `option` + `click` on the CrazyAra application so that Mac will store the executable as a trusted application. (Otherwise it will have a popup saying that it can't find the name of the developer). 

However, unfortunately, I'm still getting the error that CrazyAra does not support Crazyhouse: 
<img width="362" alt="Screen Shot 2021-02-01 at 1 03 04 PM" src="https://user-images.githubusercontent.com/308931/106498843-d31d2100-648d-11eb-8f7e-de47a22a33db.png">

**Comment by QueensGambit** [comment]
I think one also has also to replace `-fUCCI` with `-fUCCI` or to select the checkbox `USI/UCCI (uses specified -uxi Adapter) to make it work.

**Comment by DeFilippis** [comment]
Yes! It finally works! Thanks so much for all your patience. I really appreciate it. Very excited to start analyzing my games with this.
