### ISSUE TITLE
cutechess support windows 10

### ISSUE THREAD

**Issue by GregNeto** [QueensGambit/CrazyAra#31]
You write: "If the default maximum start-up time for external GUIs (e.g. cutechess) is not increased, it can happen that the GUI kills the CrazyAra process because of not responding in time."

This is happening to me. Starting it directly and then the command "isready" works. Is there a way around it? Are there other ways to match it with other engines beside the quirky command-line-uci-style?

crazyara 0.60 cuda worked very well !

Thanks for your effort!

**Comment by QueensGambit** [comment]
Hi @GregNeto ,
the long start-up is caused by the different neural network architecture which requires a longer cuDNN optimization time.
As a temporarily fix, I increased the magical timeout constants from [cutechess](https://github.com/cutechess/cutechess) in `chessengine.cpp`
*   https://github.com/cutechess/cutechess/blob/master/projects/lib/src/chessengine.cpp#L87

and rebuild cutechess afterwards. I agree that this is not very user friendly.
Maybe it would be useful to make these options modifiable in the cutechess-gui.
The start-up time only happens once if you schedule a 1v1 cutechess tournament.

Alternatively, you can use [Winboard](http://hgm.nubati.net/) ([XBoard](https://www.gnu.org/software/xboard/) for Linux/Mac) which doesn't have a timeout for loading an engine. Here it is important to select the **uci2wb** adapter rather than the default **Polygot** adapter (https://github.com/QueensGambit/CrazyAra/issues/23).

For the next release I plan to switch to the [onnx-tensorrt](https://github.com/onnx/onnx-tensorrt) back-end for GPU inference if possible.

**Comment by GregNeto** [comment]
There are new builts of cutechess in
http://talkchess.com/forum3/viewtopic.php?f=2&t=66430&hilit=cutechess&start=50

And I had a rights issue concerning the crazyara engine folders, I had to put them in my documents folder ... now it somehow works :-)

CrazyAra 070 model 45 running on my 1060 gtx notebook is the strongest crazyhouse entity, beating the newest stockfish quiet convincingly. And model 96 in the pipeline! Very impressive, congrats!

**Comment by QueensGambit** [comment]
Thank you for the feedback. I'm pleased that you managed to get the GPU version running in [cutechess](https://github.com/cutechess/cutechess).

Did **cutechess-2019-04-27-tp.zip** on http://talkchess.com/forum3/viewtopic.php?f=2&t=66430&hilit=cutechess&start=50 not include an engine time-out?

For directory and file navigation, _CrazyAra_ uses the cross-platform [dirent library](https://github.com/tronkko/dirent).
* https://github.com/QueensGambit/CrazyAra/blob/master/engine/3rdparty/dirent/dirent.h

The engine folder issue might be due to spaces in the file path.
I'll try to replicate this issue.

May I ask under what conditions you hosted the tournament (time control,  opening suite) and how much nodes per seconds (nps) your system achieved for both engines?
_CrazyAra_ usually does better relative to _Multi-Variant-Stockfish_ for longer time controls from my experience. For short time controls, decreasing `Centi_Node_Temperature` from 200 to 150 will result in less exploration and a higher playing strength.

When the TensorRT back-end is working on Windows as well, you can expect about twice the speed for the same model.

**Comment by GregNeto** [comment]
Montag meld ich mich, geh jetzt übers Wochenende in die Berge

Johannes Czech <notifications@github.com> schrieb am Fr., 10. Jän. 2020,
15:51:

**Comment by QueensGambit** [comment]
Thanks for your detailed information and links.
I'd recommend to give _Stockfish_ more threads to work with for a fairer comparison and to increase its hash-size for long time controls.

> There is a lack of fair starting positions in epd or pgn format for crazyhouse:

I also made the experience that most common cz opening positions at ply 5 give White a 100-400 centipawn (cp) advantage which is problematic for testing, especially at long time controls or strong hardware.

For the [evaluation in 0.7.0](https://github.com/QueensGambit/CrazyAra/wiki/v0.7.0), I used 50 random opening starting positions from a list of [81 openings](https://github.com/QueensGambit/CrazyAra/blob/master/etc/media/wiki/Strength_Evaluation/v0.7.0/zh-equal-long-81.pgn). The positions have been provided by [**FM** Optilink](https://lichess.org/@/optilink), aren't too exotic and mostly between -100 cp and +100 cp. I removed a few opening positions with the help of _Stockfish_ and _CrazyAra_ but there are probably still some too one-sided starting positions left. I agree that a systematic procedure could help here.
Ferdinand Mosca published `ccva-520start.pgn` in 2016 which could be worth to re-analyze as well:
* https://sites.google.com/site/zhassociation/download

> Inofficial development snapshots of Multi variant stockfish seem to regress in playing strength compared to eg sf 120919

Your results might be due to a too low sample size.

@Matuiss2 conducted a tournament (TC: 1min +1s) between a Multi-Variant-SF version from early December and the last official Multi-Variant-SF-Dev release (Nov 29, 2018) and it resulted in 
```
58 - 33 - 9 [W/L/D]
```
 in favour of SF-Dev. 

Regression tests are also continuously conducted on the **Multi-Variant Stockfish Testing Framework**:
* http://35.161.250.236:6543/regression

> i have a rather big crazyhouse rating list.

Cool, nice to hear that! I thought most people lost interest in crazyhouse engines after the CCVA Computer Championships 2016 and 2017. I also know of a cz rating list maintained by Guenther Simon:
* http://rwbc-chess.de/chronology.htm

**Comment by GregNeto** [comment]
> I'd recommend to give _Stockfish_ more threads to work with for a fairer comparison and to increase its hash-size for long time controls.

I test engines since 30 years and am a bit burned testing with too much time and/or too much cores or ponder on or other in retrospect silly stuff like testing too many SF-DEF engines which were too similar in strenghth. I want 1000s of games against several, officially published opponents.
The discussion what a "fair" comparison is only emerged with the advance of strong NN GPU-using engines. For me I first compare to my benchmark engines which are on one cpu. My hardware is limited to a quad core i7-7700 HQ notebook with a 1060gtx. Later I will add SF 10 and SF 120919 running on 3 CPU (physical cores mninus one) so to have a fair comparison on my rather typical consumer hardware. And I will test on a bit longer time control too (4+4).


> from a list of [81 openings](https://github.com/QueensGambit/CrazyAra/blob/master/etc/media/wiki/Strength_Evaluation/v0.7.0/zh-equal-long-81.pgn). The positions have been provided by [**FM** Optilink](https://lichess.org/@/optilink), aren't

These positions are the best/fairest I have seen so far, cudos. 

> Your results might be due to a too low sample size.
> 
> @Matuiss2 conducted a tournament (TC: 1min +1s) between a Multi-Variant-SF version from early December and the last official Multi-Variant-SF-Dev release (Nov 29, 2018) and it resulted in
> 
> ```
> 58 - 33 - 9 [W/L/D]
> ```
> 
> in favour of SF-Dev.

I compared with nearly thousand games, and with SF 120919, not SF 10. I prefer officially released builds. I will wait till Multi-SF 11.

**Comment by QueensGambit** [comment]
Yes, I see your point. A standardized setup is preferable when maintaining rating list, especially because most other crazyhouse engines only support single core usage.
I also like to use official releases rather than development builds.
I wasn't aware that https://github.com/niklasf/Stockfish/releases publishes new  releases at a higher frequency than https://github.com/ddugovic/Stockfish/releases.
Therefore, I used a development build for evaluation 070.

Luckily, crazyhouse is a shorter and more decisive game than chess and the effects of changes usually become apparent with a small number of games.

**Comment by GregNeto** [comment]
First strength report: both model 45 and 96 score around 62% against SF 120919 after 950 games each, thats plus 80 ELO; model 96 beats model 45 58.7% after nearly 400 games, thats 60 ELO

Just anexample how important it is to test with a lot of games against different opps.

With a time control 1 min+1sec sf uses nearly all its time, with crazyara time management can be improved a lot

So a look at the rating list (bayeselo 0052, 50000+ games, commands elo, mm 1 1, exactdist)

 Rank Name                          Elo    +    - games score oppo. draws 
   1 CrazyAra 070 1060 m96         931   19   19  1376   61%   848    2% 
   2 CrazyAra 070 1060 m45         902   19   19  1346   56%   857    2% 
   3 Stockfish 120919              827   11   11  6039   64%   690    1% 
   4 Stockfish 10                  784   12   12  4251   72%   586    2% 
   5 Stockfish 9                   771   12   12  4238   70%   587    1% 
   6 CrazyAra 060 1060 RISEv1 44   719   16   16  2464   64%   592    1% 
   7 CrazyAra 060 1060 RISEv1      683   14   14  2798   58%   611    1% 
   8 Stockfish Fairy 10.4          651   15   15  2377   51%   644    1% 
   9 Stockfish Fairy 10.3          598   12   12  3884   50%   592    1% 
  10 Stockfish Fairy 10.2          576   12   12  4246   46%   606    1% 
  11 Stockfish 280217              506   12   12  4241   37%   614    2% 
  12 Stockfish 080217              443   12   13  4103   30%   619    2% 
  13 Stockfish 091216              409   12   12  5845   50%   366    2% 
  14 Stockfish 301116              319   14   14  4655   55%   239    2% 
  15 CrazyAra 060 mkl RISEv2 44    217   22   22  1450   64%    69    0% 
  16 Stockfish 151116              154   14   15  4655   53%   109    2% 
  17 CrazyAra 060 mkl RISEv2        94   22   22  1294   63%   -19    1% 
  18 Imortal v2.21                 -60   16   16  2998   52%   -81    2% 
  19 TJchess 1.3-x64              -158   13   13  5017   59%  -263    1% 
  20 Sunsetter 9                  -241   14   14  4156   52%  -258    2% 
  21 Imortal v2.0                 -270   14   14  4217   56%  -312    1% 
  22 Sunsetter 8                  -395   16   16  2824   49%  -370    3% 
  23 TJchess 1.1-x64              -407   15   15  3215   47%  -359    1% 
  24 CrazyWa 1.0.2                -418   15   16  2593   36%  -259    1% 
  25 Imortal v1.0                 -428   14   14  3369   43%  -344    1% 
  26 Sunsetter 7g                 -442   17   17  2255   57%  -505    1% 
  27 Sjaak II 1.4.1               -514   21   21  1372   37%  -392    1% 
  28 CrazyWa 0.0.9                -522   22   22  1124   56%  -575    1% 
  29 Sjeng 11.3                   -540   19   20  1465   34%  -402    1% 
  30 NebiyuAlien_1.45a            -575   21   22  1256   38%  -477    1% 
  31 Sjaak II 1.3.1a              -612   21   21  1532   37%  -487    0% 
  32 Feuerstein 0.4.6.1           -629   20   21  1534   31%  -458    1% 
  33 NebiyuAlien_1.45             -764   24   25  1478   21%  -461    1% 
  34 Pulsar2009-9b                -805   21   21  2180   20%  -452    1% 
  35 TSCP zh 1.1                  -880   25   26  1260   21%  -568    1% 
  36 KKFChess v2.6.7beta          -918   27   28  1443   14%  -499    2%

**Comment by QueensGambit** [comment]
Wow, that's quite a list and must have taken a long time to generate, particularly because of _CrazyAra's_ current long start-up times.
I hope you don't mind that I put your results into a more readable and structured form:

Rank | Name | Elo | + | - | games | score | oppo.| draws
---  | ---  | --- | ---| --- | ---   | ---   | ---  | ---
1 | CrazyAra 070 1060 m96 | 931 | 19 | 19 | 1376 | 61% | 848 | 2%
2 | CrazyAra 070 1060 m45 | 902 | 19 | 19 | 1346 | 56% | 857 | 2%
3 | Stockfish 120919 | 827 | 11 | 11 | 6039 | 64% | 690 | 1%
4 | Stockfish 10 | 784 | 12 | 12 | 4251 | 72% | 586 | 2%
5 | Stockfish 9 | 771 | 12 | 12 | 4238 | 70% | 587 | 1%
6 | CrazyAra 060 1060 RISEv1 44 | 719 | 16 | 16 | 2464 | 64% | 592 | 1%
7 | CrazyAra 060 1060 RISEv1 | 683 | 14 | 14 | 2798 | 58% | 611 | 1%
8 | Stockfish Fairy 10.4 | 651 | 15 | 15 | 2377 | 51% | 644 | 1%
9 | Stockfish Fairy 10.3 | 598 | 12 | 12 | 3884 | 50% | 592 | 1%
10 | Stockfish Fairy 10.2 | 576 | 12 | 12 | 4246 | 46% | 606 | 1%
11 | Stockfish 280217 | 506 | 12 | 12 | 4241 | 37% | 614 | 2%
12 | Stockfish 080217 | 443 | 12 | 13 | 4103 | 30% | 619 | 2%
13 | Stockfish 091216 | 409 | 12 | 12 | 5845 | 50% | 366 | 2%
14 | Stockfish 301116 | 319 | 14 | 14 | 4655 | 55% | 239 | 2%
15 | CrazyAra 060 mkl RISEv2 44 | 217 | 22 | 22 | 1450 | 64% | 69 | 0%
16 | Stockfish 151116 | 154 | 14 | 15 | 4655 | 53% | 109 | 2%
17 | CrazyAra 060 mkl RISEv2 | 94 | 22 | 22 | 1294 | 63% | -19 | 1%
18 | Imortal v2.21 | -60 | 16 | 16 | 2998 | 52% | -81 | 2%
19 | TJchess 1.3-x64 | -158 | 13 | 13 | 5017 | 59% | -263 | 1%
20 | Sunsetter 9 | -241 | 14 | 14 | 4156 | 52% | -258 | 2%
21 | Imortal v2.0 | -270 | 14 | 14 | 4217 | 56% | -312 | 1%
22 | Sunsetter 8 | -395 | 16 | 16 | 2824 | 49% | -370 | 3%
23 | TJchess 1.1-x64 | -407 | 15 | 15 | 3215 | 47% | -359 | 1%
24 | CrazyWa 1.0.2 | -418 | 15 | 16 | 2593 | 36% | -259 | 1%
25 | Imortal v1.0 | -428 | 14 | 14 | 3369 | 43% | -344 | 1%
26 | Sunsetter 7g | -442 | 17 | 17 | 2255 | 57% | -505 | 1%
27 | Sjaak II 1.4.1 | -514 | 21 | 21 | 1372 | 37% | -392 | 1%
28 | CrazyWa 0.0.9 | -522 | 22 | 22 | 1124 | 56% | -575 | 1%
29 | Sjeng 11.3 | -540 | 19 | 20 | 1465 | 34% | -402 | 1%
30 | NebiyuAlien_1.45a | -575 | 21 | 22 | 1256 | 38% | -477 | 1%
31 | Sjaak II 1.3.1a | -612 | 21 | 21 | 1532 | 37% |  -487 | 0%
32 | Feuerstein 0.4.6.1 | -629 | 20 | 21 | 1534 | 31% | -458 | 1%
33 | NebiyuAlien_1.45 | -764 | 24 | 25 | 1478 | 21% | -461 | 1%
34 | Pulsar2009-9b | -805 | 21 | 21 | 2180 | 20% | -452 | 1%
35 | TSCP zh 1.1 | -880 | 25 | 26 | 1260 | 21% | -568 | 1%
36 | KKFChess v2.6.7beta | -918 | 27 | 28 | 1443 | 14% | -499 | 2%

I wonder what the difference between  **CrazyAra 060 mkl RISEv2 44** and **CrazyAra 060 mkl RISEv2** is.

The last time I evaluated multiple engines was in our paper (**Section 11:  Experimental Evaluation**) and for version v0.3.0 (https://github.com/QueensGambit/CrazyAra/wiki/v0.3.1) but compared to your list, these tournaments are a joke.

Sine your list includes a lot of crazyhouse engines and you put a lot of work and resources into it, you might want to share it in the lichess.org crazyhouse-engine-development group:
* https://lichess.org/team/crazyhouse-engine-development-and-game-analyses


> thats plus 80 ELO; model 96 beats model 45 58.7% after nearly 400 games, thats 60 ELO
>
> Just anexample how important it is to test with a lot of games against different opps.

Yes, I expected that direct self-play comparison is a bit inflated because both models still share similar strengths and weaknesses compared to alpha-beta engines.

> With a time control 1 min+1sec sf uses nearly all its time, with crazyara time management can be  improved a lot

You're right on this one. _CrazyAra's_ time management is still pretty basic and most of its strength is due to its neural network. I might improve it for the next release but primarily I'd like to address the current known issues first and make _CrazyAra_ more robust against a series of checks.

**Comment by QueensGambit** [comment]
I just created a small visualization of your tournament report. The plot includes error bars but due to the high number of games they are hardly recognizable.
![greg_neto_tournament](https://user-images.githubusercontent.com/15967624/72477566-1c052780-37f0-11ea-857b-64abe1b69e11.png)

**Comment by GregNeto** [comment]
Feel free to use or publish the list as you want. My English and publishing abilities are more of a hindrance for this. I want to at least add matches of the crazyaras against SF 10 and SF 9. This will take a couple of days. Then Multi SF 11 could be published, but I dont expect a lot compared to SF 120919. If you want I can put the updated lists in github somewhere, this issue seems like the wrong place.

The 44 in CrazyAra 060 1060 RISEv1 44 and CrazyAra 060 mkl RISEv2 44 means that testing has also been done with 4min+ 4 sec a game (of course also for the cpu engines). My tests concluded that results between stockfishs and the other stronger engines did not differ significantly when testing with more time, but Crazyara performed better. This pollutes the list a bit, but it is not rocket science. Maybe I will do some games with 10 seconds a move against SF running on three cores so only pure engine strenth plays a role. 

I have no problem running crazyara in cutechess, once it is started the first time I cannnot observe any delay. But of course running 24/7 only produces between 400 and 600 games a day.

What is really missing are updated epd opening files for testing, since the ianfab files are a bit outdated (SF is 150 rating points stronger than 2 or 3 years ago) and more positions (up to 10000) would be nice. For this help is needed, I lack the programming and compilation skills for this.

With non NN engines I could take the 960 (without castling) positions, but Crazyara performs much worse from these positions of course.

Just a last point if someone asks where I would put humans into the above list: 

The classic Sunsetter 8 or TJchess 1.1 gave the best humans a good fight on lichess. After the emergence of the first Stockfishs human players had no chance in tournament like conditions. This estimate is for blitz games with increment.

**Comment by QueensGambit** [comment]
> If you want I can put the updated lists in github somewhere, this issue seems like the wrong place.

You might want to publish your result via a google spreadsheet with view only access.
Alternatively, you could use a csv or txt file stored in google drive or other cloud services or a LaTex document on overleaf.com.

> With non NN engines I could take the 960 (without castling) positions, but Crazyara performs much worse from these positions of course.

Yes, _CrazyAra_ is currently not used to play cz 960 positions and expects all pieces to start from their default squares.
I trained a CNN via supervised learning on the chess960 lichess.org data set in the course of my master thesis. It didn't seem to cause many problems.
However, I'd argue that using the 960 starting positions doesn't solve the problem of White's dramatic opening advantage in crazyhouse.  On the contrary, I think in the majority of the 960 opening positions, White's advantage is even more pronounced than in the default starting position.

> Maybe I will do some games with 10 seconds a move against SF running on three cores so only pure engine strength plays a role.

Using a fixed time per move generally favours the MCTS search regime. AB engines are only able to update their position evaluation after a new depth was explored while MCTS engines can make use of every single MCTS roll-out. The computational requirement increases exponentially with respect to depth. Therefore, this aspect becomes more relevant for longer time per move or stronger hardware (e.g. the first match condition between _AlphaZero_ and _Stockfish 8_).

> Just a last point if someone asks where I would put humans into the above list:

This is a difficult question to answer because the engine hardware and time control play an important factor. Crazyhouse opening theory also evolved rapidly in recent years. Therefore, prepared human expert players seem now to be able to achieve a winning position out of the opening regardless of which engine they play. Furthermore, humans are capable of exploring and exploiting an engine's opening repertoire.

[IM opperwezen](https://lichess.org/@/opperwezen) scored a lot wins vs Stockfish on lichess.org in the past:
https://github.com/ddugovic/Stockfish/issues/380

Some of the most recent human wins vs [Stockfish / BOT GodelEscherBot](https://lichess.org/@/GodelEscherBot) were by [catask](https://lichess.org/@/catask). Note that [BOT GodelEscherBot](https://lichess.org/@/GodelEscherBot) is not running on massive hardware but is still stronger than Stockfish AI level 8 (2600):

https://lichess.org/jdZVgBQ4
https://lichess.org/Y9BBGnjN/black#0
https://lichess.org/Y8KCn0tS#0
https://lichess.org/5dnx43Rk

Some other players are also known to score a lot wins vs engines such as [Mugwort](https://lichess.org/@/Mugwort) and [TheFinnisher](https://lichess.org/@/TheFinnisher).
 [Mugwort](https://lichess.org/@/Mugwort) was the first one to score a win as Black vs [CrazyAraFish / CrazyAra 060 RISEv1 1080ti](https://lichess.org/@/CrazyAraFish):
https://lichess.org/xNKerjai

The last time I hosted _CrazyAra_ on lichess.org,
[CrazyAra / CrazyAra 060 RISEv2 1080ti](https://lichess.org/@/CrazyAra) scored +103 =1 -1 and  [CrazyAraFish / CrazyAra 060 RISEv1 1080ti](https://lichess.org/@/CrazyAraFish) scored +113 =1 -13 against humans. 
https://lichess.org/forum/general-chess-discussion/crazyara-publication?page=2

Last time, there was a problem that _CrazyAra_ played a bit too deterministic.
Surpsingly, _CrazyAra_ (only trained on human games but using a faster architecture) performed better than _CrazyAraFish_ (trained on human and Stockfish games) against humans.
I think this was due to the faster architecture and because _CrazyAra_ usually opted for positions which are harder to solve for humans.

> What is really missing are updated epd opening files for testing, since the ianfab files are a bit outdated (SF is 150 rating points stronger than 2 or 3 years ago) and more positions (up to 10000) would be nice. For this help is needed, I lack the programming and compilation skills for this.

I plan to systematically collect a large list of equal opening starting positions, preferably in pgn format, by using both _Stockfish_ and _CrazyAra_. Probably I will mine the positions based on _CrazyAra's_ raw network policy or human games to ensure that the starting positions aren't too exotic.
I'll inform you when the list is ready.

**Comment by QueensGambit** [comment]
Hi @GregNeto, 
I created a more balanced set with 691 crazyhouse opening positions using [Multi-Variant-Stockfish 11](https://github.com/niklasf/Stockfish/releases/tag/fishnet-180120) and [CrazyAra 0.7.0](https://github.com/QueensGambit/CrazyAra/releases/tag/0.7.0):
 * https://github.com/ianfab/books/pull/1

**Comment by GregNeto** [comment]
Tx, alread in use!

Exited to test any new version of your program, especially good luck for standard chess, you will get much more publicity then.

Your thesis is a good read, not that I understood more than half of it. Nice to see that you also follow Katago.

The future is in less-hardware-consuming deep-self-whatever learning methods, keep up the good work!
