### ISSUE TITLE
How to use two GPU

### ISSUE THREAD

**Issue by Nordlandia** [QueensGambit/CrazyAra#33]
Is there a command for using 2x GPUs. 

For Lc0 i use following syntax for RTX cards: (backend=cudnn-fp16,gpu=0),(backend=cudnn-fp16,gpu=1)

**Comment by QueensGambit** [comment]
Hello @Nordlandia ,
multi-gpu usage and float16 bit inference is not supported yet.
I was unable to implement and test it so far because I'm only using a single GTX1080ti.
However, I plan to buy a new GPU when the next generation is out.

**Comment by Nordlandia** [comment]
Ok. When we first talk about GPU. What settings do you recommend for RTX 2080 Super OC. 

I have two card, hence the thread title. Should i adjust threads to 7 or 8 for i7-5960X 4.5GHz.

**Comment by QueensGambit** [comment]
What is your current nps for _CrazyAra_?
I mostly tested _CrazyAra_ on my GTX 1080ti on Ubuntu 18.04.3 LTS and also used three V100 GPUs for the reinforcement learning part.

One user reported to achieve  6-7 k nps using a RTX 2080-Ti, CUDA 10.1, cuDNN v7.5.1.10 back-end  on Windows with the default UCI options.
Another Windows user with a GTX 1060 and the same back-end reported 1900 nps.

For my thesis, I conducted a speed comparison for different back-ends and model architectures (the plot shows the median nps values):

![image](https://user-images.githubusercontent.com/15967624/72899044-830d6980-3d25-11ea-964a-80f214c8b1b7.png)

-- Deep Reinforcement Learning for Crazyhouse, Johannes Czech (2019)

You can run the benchmark on your system by using:
```java
isready
benchmark 3000
```
from the cmd-line.

On my laptop with an Intel® CoreTM i5-8250U CPU @ 1.60GHz, IntelMKL back-end and model-os-45-risev2, this results in the following output:
```java
Summary
----------------------
Passed:		9/15
NPS (avg):	323
NPS (median):	321
PV-Depth:	16
```

The benchmark positions are currently defined here:
https://github.com/QueensGambit/CrazyAra/blob/master/engine/src/tests/benchmarkpositions.cpp#L29

```C++
TestPosition( string fen, string blunderMove, string alternativeMove);
```

These positions are quite tactical and were challenging to solve with _CrazyAra_ in the past.
Note, _CrazyAra_ does not use the history information of previous moves, therefore a single FEN is sufficient as input.

Float16 inference and TensorRT support is unfortunately not available for Windows yet.
I'd recommend to check your GPU utilization (`nvidia-smi` / Task-Manager for Windows) during a search and try out different **Batch_Size** and **Threads** values.
If you increase **Threads** to e.g. 4 or more, you might also want to reduce **Virtual_Loss** to e.g. 2.
The maximum nodes for a search is by default capped at 1.5 million nodes to avoid unlimited memory allocation and in order to reproduce the same setup as in [Strength Evaluation v0.7.0](https://github.com/QueensGambit/CrazyAra/wiki/v0.7.0).
You can change this value by:
```java
setoption name Nodes value <N>
isready
```

**Comment by QueensGambit** [comment]
@Nordlandia Multi-GPU has now been implemented: https://github.com/QueensGambit/CrazyAra/commit/4426059659eae420ceeff59ded8f53198d3ad409

The UCI-option `Threads` has been renamed into `Threads_per_Device`.
The option `Device_ID` has been replaced by `First_Device_ID` and `Last_Device_ID`.
This way _CrazyAra_ will use all GPUs with a device id of:
 `First_Device_ID` <= Device ID <=  `Last_Device_ID`.

This way, all GPUs use the same precision backend (float32, float16, int8) and batch size.
Would you recommend allowing different batch sizes and precisions for each GPU?

# NPS Benchmark 

In the following, a short nps benchmark to validate the scaling for multi-gpus.

UCI-Options:
* UCI_Variant: crazyhouse
* Batch_Size: 16
* Precision: float16
* Model_Directory: model_os_96/

```
benchmark 3000
```

## RTX 2070 Super OC
* First_Device_ID: 0
* Last_Device_ID: 0

```java
Summary
----------------------
Passed:		11/15
NPS (avg):	31526
NPS (median):	23191
PV-Depth:	36
```

## GTX 1080ti
* First_Device_ID: 1
* Last_Device_ID: 1

```java
Summary
----------------------
Passed:		10/15
NPS (avg):	12225
NPS (median):	9034
PV-Depth:	33
```


## RTX 2070 Super OC + GTX 1080ti
* First_Device_ID: 0
* Last_Device_ID: 1

```java
Summary
----------------------
Passed:		11/15
NPS (avg):	45633
NPS (median):	33302
PV-Depth:	39
```

**Comment by Nordlandia** [comment]
Much appreciated. 

I'm not so sure about that one. I'm not the one that can answer on that question. Maybe contact lc0 folks at discord.
