### ISSUE TITLE
CrazyAra delays printing results even when node limit has been reached

### ISSUE THREAD

**Issue by catask** [QueensGambit/CrazyAra#38]
Not a huge issue, but CrazyAra prints the result of the analysis after the end of the movetime, even when the analysis node limit has been reached. If there is a gap in time, the engine stops analyzing until the movetime limit has been reached, only then it prints out the result. Also had trouble getting go node <value> working, seems that the engine only accept a movetime.

**Comment by QueensGambit** [comment]
You're right. This was a bug in release 0.7.0 and has already been fixed in the current development version for release 0.8.0.
Moreover, the current principal variation is now logged every second and also reports the number of table base hits.
The last thing I want to add is to support the `go infinite` command for infinite analysis.
This also requires asynchronous handling of the user's std-input via the `stop` and `quit` command.
Release 0.7.0 did not allow the current search to be stopped arbitrarily.
