### ISSUE TITLE
Something wrong with lichess-bot program

### ISSUE THREAD

**Issue by eldebarva** [QueensGambit/CrazyAra#40]
For some reason, CrazyAra is the only engine that I cant make it play on lichess, whenever I start a game, lichess-bot console shows me, after 20 minutes, this message 

![crazyara error](https://user-images.githubusercontent.com/45858194/82288690-4adb0800-9960-11ea-9e66-c7818d93aa67.PNG)

I know this has to be a problem of the lichess-bot program, (i have succesfuly played vs CrazyAra at cutechess UCI) but since their github page is basically abandoned, I want to know if you can help me with this issue.

**Comment by QueensGambit** [comment]
Hi @eldebarva ,
great that you try out hosting _CrazyAra_ on lichess.
Normally, _CrazyAra_ should start very fast, given you have already run the command `isready` once successfully. I think the problem might the folder structure.
For the last hosting of _CrazyAra_ (17.05.2020-18.05.2020), I used the following structure:
```
lichess-bot/
├── engines
├── model
```
The `engines` directory contains the _CrazyAra_ executable and the `model`directory contains the ONNX and trt files. Lichess-bot sees the directoy where you start `python lichess-bot.py` as the current working directory.

Last time, I also experienced that sometimes when e.g. people abort games, last executables weren't always closed correctly allocating additional RAM over time. I assume that this is not correctly handled by the current lichess-bot version because for older version this worked fine and the quit and stop command are supported.

Best regards,
~QueensGambit

**Comment by eldebarva** [comment]
Oh, that was the problem, thank you so much! One last question, for tweaking parameters in order to make CrazyAra play faster or slower depending on the time control, do you use config.yml or do you tweak them directly into the command line interface of the engine?

**Comment by QueensGambit** [comment]
Yes, you can set your custom UCI-options in the `config.yml` file by passing a dictionary object like this: https://github.com/ShailChoksi/lichess-bot/blob/master/config.yml.default#L25
```yml
uci_options: {First_Device_ID: 0, Last_Device_ID: 1, Move_Overhead: 500, Log_File: 'CrazyAra.log'}
```
You don't need to change `First_Device_ID` and `Last_Device_ID` for single GPU usage.
By `Centi_Temperature` you can control the shape of the MCTS policy distribution also.
Higher values lead to more sampling here.
`Centi_Quantile_Clipping` clips the lower quantile (default: 25%) to reduce the chance of sampling really bad moves.

The time manager handles all different time controls automatically and takes the given hardware into account. The only option to change is to increase `Move_Overhead` to avoid getting flagged because of lichess` additional delay for BOT accounts and your internet connection.

Currently, _CrazyAra_ expects the UCI-options to be set before the `isready` command.
I plan to enable to change UCI options at an arbitrary time point in the next release.

The UCI-option `Log_File` creates a log file to which all stdin and stdout of _CrazyAra_ is getting logged. By default no `Log_File` is used in release 0.8.0.

**Comment by eldebarva** [comment]
I was having a lot of trouble with my bot flagging, I had to set the upper limit of nodes for it to be fast enough. The solution was simple, just downloaded lichess-bot noobpwnftw version https://github.com/ShailChoksi/lichess-bot/tree/6fda9cb4f57933eea2aff391cec6ebac72c2d754 and now everything is working perfectly! Again thanks for your help!

**Comment by QueensGambit** [comment]
@eldebarva You may also want to try the INT8 backend.
It is still experimental but it should increase the NPS for older non RTX-GPUs by more than 200%.

For the first start, I recommend to set it via the command line:
This can be enabled by the option:
`setoption name Precision value int8`
`isready`
After some minutes it should have generated the `int8` trt-files in the model directory and you can enable it like the other UCI-options in the [config.yml](https://github.com/ShailChoksi/lichess-bot/blob/master/config.yml.default#L25) file: 
```python
uci_options: {Precision: 'int8', First_Device_ID: 0, Last_Device_ID: 1, Move_Overhead: 500, Log_File: 'CrazyAra.log'}
```

**Comment by eldebarva** [comment]
done :)

**Comment by QueensGambit** [comment]
It usually takes several minutes to generate the trt files but afterwards if the trt files are in the model directory it should load as fast as for float16.
Therefore, you can use the command line for starting it first:
-> Navigate to the CrazyAra directory
Shift + Right Mouse Click -> Open Power Shell Here
```bash
CrazyAra.exe
setoption name Precision value int8
isready
```
After some time it should return `readyok` and you should see the files:
`model-bsize1-int8-0.trt`
`model-bsize16-int8-0.trt`
in the `model/` directory.

Unfortunately, I'm not able to ship my trt files within the release because the TensorRT optimization is hardware specific.

**Comment by eldebarva** [comment]
oh yes, it took several minutes but at the end it started playing. So this option makes engine faster, but weaker, is that right?

**Comment by QueensGambit** [comment]
Yes, the NPS should increase by more than 200% for older GPUs, non RTX cards.
However, the network evaluations are slightly less accurate due to loss of precision.
It also requires a calibration phase to detect the right scaling ranges.
I haven't done much evaluation for it in crazyhouse but it seemed stronger in TC: **30s + 0.1s**:
```python
Score of CrazyAra-0.8.0-INT8-GTX1080ti vs CrazyAra-0.8.0-FP16-GTX1080ti: 72 - 17 - 11 [0.775]
Elo difference: 214.8 +/- 77.1, LOS: 100.0 %, DrawRatio: 11.0 %

100 of 100 games finished.
```
