### ISSUE TITLE
CrazyAra not finding engine file

### ISSUE THREAD

**Issue by Belzedar94** [QueensGambit/CrazyAra#54]
Good morning,

I was trying to set up CrazyAra (0.8) in the latest Cuteches GUI (1.2) but every time I try it, I got the "no response to ping" issue (https://gyazo.com/2052c36524cc40d286f93d4264cfd9df).

If I manually execute CrazyAra.exe, everything seems fine (https://gyazo.com/3953caf74e1271388a53f87ad1ad6e68), executing UCI command, everything seems fine as well (https://gyazo.com/2d06c3cbc1d436e9272073a5a6ae64e1).

But when trying to execute isready, seems like somehow models and parameters aren't found (https://gyazo.com/d3ef071af42a1096a28a2748a6443882). Readyok is not printed, so I assume the error is here.

I'm running on Windows 10, i7-9750h + RTX2080.

I haven't moved model files. Only extracted the zip as it is in the 0.8.0 release. (https://gyazo.com/fc224abdf5aed5879264a87faac9cabf) (https://gyazo.com/8e116afd5b7484af1c1b14358d2e52a2)

Thanks for the support.

Best regards

**Comment by QueensGambit** [comment]
Hello @Belzedar94 ,

> But when trying to execute isready, seems like somehow models and parameters aren't found (https://gyazo.com/d3ef071af42a1096a28a2748a6443882). Readyok is not printed, so I assume the error is here.

The process seems to working fine but only need to require more time on first start-up.
I haven't tried generating the trt-files on a RTX2080, yet but I assume that the process may take longer (maybe up to 15min) on newer GPU cards because more optimization routines are available.

> The first start-up time of _CrazyAra_ can take several minutes to generate the trt hardware specific engine files.
All later start-ups should be fast e.g. < 3s. The TensorRT files are stored in the Model_Directory.

After `isready` the trt-files are being generated. The trt-files are hardware specific optimization files which is why we can't ship them.
I can look into finding a better configuration to speed-up this process or at least make it more transparent to the user.

Best regards,
~QueensGambit

**Comment by Belzedar94** [comment]
Hello @QueensGambit ,

Thanks for the clarification. Yes, after waiting, try files are generating and readyok is printed. However, when trying to run them on Lichess, they run out of time, causing the "no response to ping" error to pop up when trying to initialize a match or tournament. I wouldn't expect the engine to run out of time at start if the trt files are already generated after the first start-up.

**Comment by QueensGambit** [comment]
Hmm, yes after the trt-files have been generated, the loading process should be fast.
Do you see a response after typing.
`isready`
`go`
from the command-line?

My guess is that the binary does not find the `Model_Directory` because of the `Working Directory` configuration in cutechess.
The binary looks for a directory called `model` relative to its `Working Directory`.
It should be something like:
**Command** `CrazyAra.exe`
 **Working Directory** `C:\Users\Username\Download\CrazyAra_0.8.0_Win_TensorRT\CrazyAra_0.8.0_Win_TensorRT`
 
Attached a screenshot on how to configure the older python version in cutechess: 
https://raw.githubusercontent.com/QueensGambit/CrazyAra/master/etc/media/wiki/Install_Guide/add_engine_win10.PNG

**Comment by Belzedar94** [comment]
After typing isready and go: https://gyazo.com/9323b1f7d3b54da3e90985b62a70bf4e

Configuring in Cutechess: https://gyazo.com/0fea2845d892da3f0df7e43984b2c316
Engine folder: https://gyazo.com/f28b21a122556e00abf8b5ff40e7ba3a

I would say everything looks good. Also, Cutechess is detecting UCI parameters of CrazyAra, so I'm not sure where is the issue once the tournament starts.

**Comment by QueensGambit** [comment]
Ok, so it seems to work properly from cmd.exe at least.
I don't see an apparent problem in the configuration, right now.

There a few things you could try out:
1) Increase the `Scale Timeouts` variable in Cutechess.
2) Try out an older version of Cutechess (e.g. [CuteChess 1.10](https://github.com/cutechess/cutechess/releases/tag/gui-1.0.0)).
3) Try configuring _CrazyAra_ in [WinBoard](http://hgm.nubati.net/).
3) Move _CrazyAra_ to a different directory and import it again.
